spring:
  application:
    name: vpp-web
  cloud:
    discovery:
      enabled: true

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: vpp-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  logging:
    level:
      org.springframework.web:DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka